using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PMCPointTool
{
    public class PointConstant
    {
        public const string ALLDATA_R = "_ALLDATA_R";
        public const string DEVICEUP = "_DEVICEUP";
        public const string ONLYONE_W = "_ONLYONE_W";
        public const string GLOBAL__R = "_GLOBAL__R";
        public const string VERSION_R = "_VERSION_R";
        public const string STATION_ALARM = "_STATION_ALARM";
        public const string STATION_PROD = "_STATION_PROD";
        public const string MF00000_R = "_MF00000_R";
        public const string WN00000_R = "_WN00000_R";
        public const string CONFIGR_R = "_CONFIGR_R";
        public const string CLS_SHIFT_ALL_W = "_CLS_SHIFT_ALL_W";
        public const string CLS_SHIFT_1_W = "_CLS_SHIFT_1_W";
        public const string CLS_SHIFT_2_W = "_CLS_SHIFT_2_W";
        public const string CLS_SHIFT_3_W = "_CLS_SHIFT_3_W";
        public const string WORK_SHIFT_1_W = "_WORK_SHIFT_1_W";
        public const string WORK_SHIFT_2_W = "_WORK_SHIFT_2_W";
        public const string WORK_SHIFT_3_W = "_WORK_SHIFT_3_W";
        public const string WORK_SHIFT_W = "_WORK_SHIFT_W";
        public const string RT00000_R = "_RT00000_R";
        public const string HC00000_R = "_HC00000_R";
        public const string BD00001_R = "_BD00001_R";
        public const string BD00002_R = "_BD00002_R";
        public const string BD00003_R = "_BD00003_R";
        public const string SD00001_R = "_SD00001_R";
        public const string SD00002_R = "_SD00002_R";
        public const string SD00003_R = "_SD00003_R";
        public const string MD00001_R = "_MD00001_R";
        public const string MD00002_R = "_MD00002_R";
        public const string MD00003_R = "_MD00003_R";
        public const string PD00001_R = "_PD00001_R";
        public const string PD00002_R = "_PD00002_R";
        public const string PD00003_R = "_PD00003_R";
        public const string ED00001_R = "_ED00001_R";
        public const string ED00002_R = "_ED00002_R";
        public const string ED00003_R = "_ED00003_R";
        public const string AD00001_R = "_AD00001_R";
        public const string AD00002_R = "_AD00002_R";
        public const string AD00003_R = "_AD00003_R";
        public const string OD00001_R = "_OD00001_R";
        public const string OD00002_R = "_OD00002_R";
        public const string OD00003_R = "_OD00003_R";
        public const string CD00001_R = "_CD00001_R";
        public const string CD00002_R = "_CD00002_R";
        public const string CD00003_R = "_CD00003_R";
        public const string FD00001_R = "_FD00001_R";
        public const string FD00002_R = "_FD00002_R";
        public const string FD00003_R = "_FD00003_R";
        public const string BTRIGER_R = "_BTRIGER_R";
        public const string STRIGER_R = "_STRIGER_R";
        public const string MTRIGER_R = "_MTRIGER_R";
        public const string PTRIGER_R = "_PTRIGER_R";
        public const string ETRIGER_R = "_ETRIGER_R";
        public const string ATRIGER_R = "_ATRIGER_R";
        public const string OTRIGER_R = "_OTRIGER_R";
        public const string CTRIGER_R = "_CTRIGER_R";
        public const string FTRIGER_R = "_FTRIGER_R";
        public const string ACOUNT__R = "_ACOUNT__R";
        public const string BCOUNT__R = "_BCOUNT__R";
        public const string CCOUNT__R = "_CCOUNT__R";
        public const string ECOUNT__R = "_ECOUNT__R";
        public const string FCOUNT__R = "_FCOUNT__R";
        public const string MCOUNT__R = "_MCOUNT__R";
        public const string OCOUNT__R = "_OCOUNT__R";
        public const string PCOUNT__R = "_PCOUNT__R";
        public const string SCOUNT__R = "_SCOUNT__R";
        public const string ATRIGER_V = "_ATRIGER_V";
        public const string BTRIGER_V = "_BTRIGER_V";
        public const string CTRIGER_V = "_CTRIGER_V";
        public const string ETRIGER_V = "_ETRIGER_V";
        public const string FTRIGER_V = "_FTRIGER_V";
        public const string MTRIGER_V = "_MTRIGER_V";
        public const string OTRIGER_V = "_OTRIGER_V";
        public const string PTRIGER_V = "_PTRIGER_V";
        public const string STRIGER_V = "_STRIGER_V";
        public const string CLS_SHIFT_R = "_CLS_SHIFT_R";
        public const string PCA0001_R = "_PCA0001_R";
        public const string PCA0002_R = "_PCA0002_R";
        public const string PCA0003_R = "_PCA0003_R";
        public const string PCB0001_R = "_PCB0001_R";
        public const string PCB0002_R = "_PCB0002_R";
        public const string PCB0003_R = "_PCB0003_R";
        public const string PCC0001_R = "_PCC0001_R";
        public const string PCC0002_R = "_PCC0002_R";
        public const string PCC0003_R = "_PCC0003_R";
        public const string PCD0001_R = "_PCD0001_R";
        public const string PCD0002_R = "_PCD0002_R";
        public const string PCD0003_R = "_PCD0003_R";
        public const string BC00001_R = "_BC00001_R";
        public const string BC00002_R = "_BC00002_R";
        public const string BC00003_R = "_BC00003_R";
        public const string BC00004_R = "_BC00004_R";
        public const string AD00000_R = "_AD00000_R";
        public const string BD00000_R = "_BD00000_R";
        public const string CD00000_R = "_CD00000_R";
        public const string ED00000_R = "_ED00000_R";
        public const string FD00000_R = "_FD00000_R";
        public const string MD00000_R = "_MD00000_R";
        public const string OD00000_R = "_OD00000_R";
        public const string PD00000_R = "_PD00000_R";
        public const string SD00000_R = "_SD00000_R";
        public const string PCA0000_R = "_PCA0000_R";
        public const string PCB0000_R = "_PCB0000_R";
        public const string PCC0000_R = "_PCC0000_R";
        public const string PCD0000_R = "_PCD0000_R";
        public const string FDMIN00_R = "_FDMIN00_R";
        public const string MTTR = "_MTTR";
        public const string MCBF = "_MCBF";
        public const string PC00001_R = "_PC00001_R";
        public const string PC00002_R = "_PC00002_R";
        public const string PC00003_R = "_PC00003_R";
        public const string PC00000_R = "_PC00000_R";

        //TIP POINT
        public const string TIP_RDY_CYCLETIME = "_TIP_RDY_CYCLETIME";
        public const string TIP_FLT_BLOCK = "_TIP_FLT_BLOCK";
        public const string TIP_FLT_STARVE = "_TIP_FLT_STARVE";
        public const string TIP_FLT_MACHINE = "_TIP_FLT_MACHINE";
        public const string TIP_FLT_PSTOP = "_TIP_FLT_PSTOP";
        public const string TIP_FLT_ESTOP = "_TIP_FLT_ESTOP";
        public const string TIP_FLT_ANDON = "_TIP_FLT_ANDON";
        public const string TIP_FLT_OTHER = "_TIP_FLT_OTHER";
        public const string TIP_FLT_OVERCYCLE = "_TIP_FLT_OVERCYCLE";
        public const string TIP_FLT_ALL = "_TIP_FLT_ALL";
        public const string TIP_VAL_CYCLETIME = "_TIP_VAL_CYCLETIME";
        public const string TIP_VAL_PC00001 = "_TIP_VAL_PC00001";
        public const string TIP_VAL_PC00002 = "_TIP_VAL_PC00002";
        public const string TIP_VAL_PC00003 = "_TIP_VAL_PC00003";
        public const string TIP_VAL_CT = "_TIP_VAL_CT";
        public const string TAKEON__R = "_TAKEON__R";
        public const string VM00000_R = "_VM00000_R";
        public const string TIP_VAL_CURRENT_CYCLETIME = "_TIP_VAL_CURRENT_CT";
    }
}
