using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PMCPointTool
{
    /// <summary>
    /// 点属性字段类
    /// </summary>
    public class PointAttrFiled
    {
        string pt_id = "PT_ID";
        string access = "ACCESS";
        string access_filter = "ACCESS_FILTER";
        string ack_timeout_hi = "ACK_TIMEOUT_HI";
        string ack_timeout_hihi = "ACK_TIMEOUT_HIHI";
        string ack_timeout_lo = "ACK_TIMEOUT_LO";
        string ack_timeout_lolo = "ACK_TIMEOUT_LOLO";
        string addr = "ADDR";
        string addr_offset = "ADDR_OFFSET";
        string addr_type = "ADDR_TYPE";
        string alarm_changeapproval = "ALARM_CHANGEAPPROVAL";
        string alarm_delay_hi = "ALARM_DELAY_HI";
        string alarm_delay_hihi = "ALARM_DELAY_HIHI";
        string alarm_delay_lo = "ALARM_DELAY_LO";
        string alarm_delay_lolo = "ALARM_DELAY_LOLO";
        string alarm_delay_unit_hi = "ALARM_DELAY_UNIT_HI";
        string alarm_delay_unit_hihi = "ALARM_DELAY_UNIT_HIHI";
        string alarm_delay_unit_lo = "ALARM_DELAY_UNIT_LO";
        string alarm_delay_unit_lolo = "ALARM_DELAY_UNIT_LOLO";
        string alarm_publish = "ALARM_PUBLISH";
        string alm_class = "ALM_CLASS";
        string alm_criteria = "ALM_CRITERIA";
        string alm_deadband = "ALM_DEADBAND";
        string alm_delay = "ALM_DELAY";
        string alm_enable = "ALM_ENABLE";
        string alm_high_1 = "ALM_HIGH_1";
        string alm_high_2 = "ALM_HIGH_2";
        string alm_hlp_file = "ALM_HLP_FILE";
        string alm_low_1 = "ALM_LOW_1";
        string alm_low_2 = "ALM_LOW_2";
        string alm_msg = "ALM_MSG";
        string alm_route_oper = "ALM_ROUTE_OPER";
        string alm_route_sysmgr = "ALM_ROUTE_SYSMGR";
        string alm_route_user = "ALM_ROUTE_USER";
        string alm_severity = "ALM_SEVERITY";
        string alm_str = "ALM_STR";
        string alm_type = "ALM_TYPE";
        string alm_update_value = "ALM_UPDATE_VALUE";
        string analog_deadband = "ANALOG_DEADBAND";
        string bfr_count = "BFR_COUNT";
        string bfr_dur = "BFR_DUR";
        string bfr_event_period = "BFR_EVENT_PERIOD";
        string bfr_event_pt_id = "BFR_EVENT_PT_ID";
        string bfr_event_type = "BFR_EVENT_TYPE";
        string bfr_event_units = "BFR_EVENT_UNITS";
        string bfr_gate_cond = "BFR_GATE_COND";
        string bfr_sync_time = "BFR_SYNC_TIME";
        string calc_type = "CALC_TYPE";
        string changeapproval = "CHANGEAPPROVAL";
        string conv_lim_high = "CONV_LIM_HIGH";
        string conv_lim_low = "CONV_LIM_LOW";
        string conv_type = "CONV_TYPE";
        string delay_load = "DELAY_LOAD";
        string delete_req_hi = "DELETE_REQ_HI";
        string delete_req_hihi = "DELETE_REQ_HIHI";
        string delete_req_lo = "DELETE_REQ_LO";
        string delete_req_lolo = "DELETE_REQ_LOLO";
        string desc = "DESC ";
        string deviation_pt = "DEVIATION_PT";
        string device_id = "DEVICE_ID";
        string disp_lim_high = "DISP_LIM_HIGH";
        string disp_lim_low = "DISP_LIM_LOW";
        string disp_type = "DISP_TYPE";
        string disp_width = "DISP_WIDTH";
        string elements = "ELEMENTS";
        string eng_units = "ENG_UNITS";
        string enum_id = "ENUM_ID";
        string equation = "EQUATION";
        string extra = "EXTRA";
        string fw_conv_eq = "FW_CONV_EQ";
        string gr_screen = "GR_SCREEN";
        string init_val = "INIT_VAL";
        string justification = "JUSTIFICATION";
        string level = "LEVEL";
        string local = "LOCAL";
        string log_ack_hi = "LOG_ACK_HI";
        string log_ack_hihi = "LOG_ACK_HIHI";
        string log_ack_lo = "LOG_ACK_LO";
        string log_ack_lolo = "LOG_ACK_LOLO";
        string log_data = "LOG_DATA";
        string log_del_hi = "LOG_DEL_HI";
        string log_del_hihi = "LOG_DEL_HIHI";
        string log_del_lo = "LOG_DEL_LO";
        string log_del_lolo = "LOG_DEL_LOLO";
        string log_gen_hi = "LOG_GEN_HI";
        string log_gen_hihi = "LOG_GEN_HIHI";
        string log_gen_lo = "LOG_GEN_LO";
        string log_gen_lolo = "LOG_GEN_LOLO";
        string log_reset_hi = "LOG_RESET_HI";
        string log_reset_hihi = "LOG_RESET_HIHI";
        string log_reset_lo = "LOG_RESET_LO";
        string log_reset_lolo = "LOG_RESET_LOLO";
        string max_stacked = "MAX_STACKED";
        string measurement_unit_id = "MEASUREMENT_UNIT_ID";
        string misc_flags = "MISC_FLAGS";
        string poll_after_set = "POLL_AFTER_SET";
        string precision = "PRECISION";
        string proc_id = "PROC_ID";
        string ptmgmt_proc_id = "PTMGMT_PROC_ID";
        string pt_enabled = "PT_ENABLED";
        string pt_origin = "PT_ORIGIN";
        string pt_set_interval = "PT_SET_INTERVAL";
        string pt_set_time = "PT_SET_TIME";
        string pt_type = "PT_TYPE";
        string range_high = "RANGE_HIGH";
        string range_low = "RANGE_LOW";
        string raw_lim_high = "RAW_LIM_HIGH";
        string raw_lim_low = "RAW_LIM_LOW";
        string rep_timeout_hi = "REP_TIMEOUT_HI";
        string rep_timeout_hihi = "REP_TIMEOUT_HIHI";
        string rep_timeout_lo = "REP_TIMEOUT_LO";
        string rep_timeout_lolo = "REP_TIMEOUT_LOLO";
        string reset_allowed_hi = "RESET_ALLOWED_HI";
        string reset_allowed_hihi = "RESET_ALLOWED_HIHI";
        string reset_allowed_lo = "RESET_ALLOWED_LO";
        string reset_allowed_lolo = "RESET_ALLOWED_LOLO";
        string reset_cond = "RESET_COND";
        string reset_pt = "RESET_PT";
        string reset_timeout_hi = "RESET_TIMEOUT_HI";
        string reset_timeout_hihi = "RESET_TIMEOUT_HIHI";
        string reset_timeout_lo = "RESET_TIMEOUT_LO";
        string reset_timeout_lolo = "RESET_TIMEOUT_LOLO";
        string resource_id = "RESOURCE_ID";
        string rev_conv_eq = "REV_CONV_EQ";
        string rollover_val = "ROLLOVER_VAL";
        string safety_pt = "SAFETY_PT";
        string sample_intv = "SAMPLE_INTV";
        string sample_intv_unit = "SAMPLE_INTV_UNIT";
        string scan_rate = "SCAN_RATE";
        string setpoint_high = "SETPOINT_HIGH";
        string setpoint_low = "SETPOINT_LOW";
        string time_of_day = "TIME_OF_DAY";
        string trig_ck_pt = "TRIG_CK_PT";
        string trig_pt = "TRIG_PT";
        string trig_rel = "TRIG_REL";
        string trig_val = "TRIG_VAL";
        string uafset = "UAFSET";
        string update_criteria = "UPDATE_CRITERIA";
        string variance_val = "VARIANCE_VAL";
        string vars = "VARS";

        public string Pt_id
        {
            get { return pt_id; }
            set { pt_id = value; }
        }
        public string Access { get { return access; } set { access = value; } }
        public string Access_filter { get { return access_filter; } set { access_filter = value; } }
        public string Ack_timeout_hi { get { return ack_timeout_hi; } set { ack_timeout_hi = value; } }
        public string Ack_timeout_hihi { get { return ack_timeout_hihi; } set { ack_timeout_hihi = value; } }
        public string Ack_timeout_lo { get { return ack_timeout_lo; } set { ack_timeout_lo = value; } }
        public string Ack_timeout_lolo { get { return ack_timeout_lolo; } set { ack_timeout_lolo = value; } }
        public string Addr { get { return addr; } set { addr = value; } }
        public string Addr_offset { get { return addr_offset; } set { addr_offset = value; } }
        public string Addr_type { get { return addr_type; } set { addr_type = value; } }
        public string Alarm_changeapproval { get { return alarm_changeapproval; } set { alarm_changeapproval = value; } }
        public string Alarm_delay_hi { get { return alarm_delay_hi; } set { alarm_delay_hi = value; } }
        public string Alarm_delay_hihi { get { return alarm_delay_hihi; } set { alarm_delay_hihi = value; } }
        public string Alarm_delay_lo { get { return alarm_delay_lo; } set { alarm_delay_lo = value; } }
        public string Alarm_delay_lolo { get { return alarm_delay_lolo; } set { alarm_delay_lolo = value; } }
        public string Alarm_delay_unit_hi { get { return alarm_delay_unit_hi; } set { alarm_delay_unit_hi = value; } }
        public string Alarm_delay_unit_hihi { get { return alarm_delay_unit_hihi; } set { alarm_delay_unit_hihi = value; } }
        public string Alarm_delay_unit_lo { get { return alarm_delay_unit_lo; } set { alarm_delay_unit_lo = value; } }
        public string Alarm_delay_unit_lolo { get { return alarm_delay_unit_lolo; } set { alarm_delay_unit_lolo = value; } }
        public string Alarm_publish { get { return alarm_publish; } set { alarm_publish = value; } }
        public string Alm_class { get { return alm_class; } set { alm_class = value; } }
        public string Alm_criteria { get { return alm_criteria; } set { alm_criteria = value; } }
        public string Alm_deadband { get { return alm_deadband; } set { alm_deadband = value; } }
        public string Alm_delay { get { return alm_delay; } set { alm_delay = value; } }
        public string Alm_enable { get { return alm_enable; } set { alm_enable = value; } }
        public string Alm_high_1 { get { return alm_high_1; } set { alm_high_1 = value; } }
        public string Alm_high_2 { get { return alm_high_2; } set { alm_high_2 = value; } }
        public string Alm_hlp_file { get { return alm_hlp_file; } set { alm_hlp_file = value; } }
        public string Alm_low_1 { get { return alm_low_1; } set { alm_low_1 = value; } }
        public string Alm_low_2 { get { return alm_low_2; } set { alm_low_2 = value; } }
        public string Alm_msg { get { return alm_msg; } set { alm_msg = value; } }
        public string Alm_route_oper { get { return alm_route_oper; } set { alm_route_oper = value; } }
        public string Alm_route_sysmgr { get { return alm_route_sysmgr; } set { alm_route_sysmgr = value; } }
        public string Alm_route_user { get { return alm_route_user; } set { alm_route_user = value; } }
        public string Alm_severity { get { return alm_severity; } set { alm_severity = value; } }
        public string Alm_str { get { return alm_str; } set { alm_str = value; } }
        public string Alm_type { get { return alm_type; } set { alm_type = value; } }
        public string Alm_update_value { get { return alm_update_value; } set { alm_update_value = value; } }
        public string Analog_deadband { get { return analog_deadband; } set { analog_deadband = value; } }
        public string Bfr_count { get { return bfr_count; } set { bfr_count = value; } }
        public string Bfr_dur { get { return bfr_dur; } set { bfr_dur = value; } }
        public string Bfr_event_period { get { return bfr_event_period; } set { bfr_event_period = value; } }
        public string Bfr_event_pt_id { get { return bfr_event_pt_id; } set { bfr_event_pt_id = value; } }
        public string Bfr_event_type { get { return bfr_event_type; } set { bfr_event_type = value; } }
        public string Bfr_event_units { get { return bfr_event_units; } set { bfr_event_units = value; } }
        public string Bfr_gate_cond { get { return bfr_gate_cond; } set { bfr_gate_cond = value; } }
        public string Bfr_sync_time { get { return bfr_sync_time; } set { bfr_sync_time = value; } }
        public string Calc_type { get { return calc_type; } set { calc_type = value; } }
        public string Changeapproval { get { return changeapproval; } set { changeapproval = value; } }
        public string Conv_lim_high { get { return conv_lim_high; } set { conv_lim_high = value; } }
        public string Conv_lim_low { get { return conv_lim_low; } set { conv_lim_low = value; } }
        public string Conv_type { get { return conv_type; } set { conv_type = value; } }
        public string Delay_load { get { return delay_load; } set { delay_load = value; } }
        public string Delete_req_hi { get { return delete_req_hi; } set { delete_req_hi = value; } }
        public string Delete_req_hihi { get { return delete_req_hihi; } set { delete_req_hihi = value; } }
        public string Delete_req_lo { get { return delete_req_lo; } set { delete_req_lo = value; } }
        public string Delete_req_lolo { get { return delete_req_lolo; } set { delete_req_lolo = value; } }
        public string Desc { get { return desc; } set { desc = value; } }
        public string Deviation_pt { get { return deviation_pt; } set { deviation_pt = value; } }
        public string Device_id { get { return device_id; } set { device_id = value; } }
        public string Disp_lim_high { get { return disp_lim_high; } set { disp_lim_high = value; } }
        public string Disp_lim_low { get { return disp_lim_low; } set { disp_lim_low = value; } }
        public string Disp_type { get { return disp_type; } set { disp_type = value; } }
        public string Disp_width { get { return disp_width; } set { disp_width = value; } }
        public string Elements { get { return elements; } set { elements = value; } }
        public string Eng_units { get { return eng_units; } set { eng_units = value; } }
        public string Enum_id { get { return enum_id; } set { enum_id = value; } }
        public string Equation { get { return equation; } set { equation = value; } }
        public string Extra { get { return extra; } set { extra = value; } }
        public string Fw_conv_eq { get { return fw_conv_eq; } set { fw_conv_eq = value; } }
        public string Gr_screen { get { return gr_screen; } set { gr_screen = value; } }
        public string Init_val { get { return init_val; } set { init_val = value; } }
        public string Justification { get { return justification; } set { justification = value; } }
        public string Level { get { return level; } set { level = value; } }
        public string Local { get { return local; } set { local = value; } }
        public string Log_ack_hi { get { return log_ack_hi; } set { log_ack_hi = value; } }
        public string Log_ack_hihi { get { return log_ack_hihi; } set { log_ack_hihi = value; } }
        public string Log_ack_lo { get { return log_ack_lo; } set { log_ack_lo = value; } }
        public string Log_ack_lolo { get { return log_ack_lolo; } set { log_ack_lolo = value; } }
        public string Log_data { get { return log_data; } set { log_data = value; } }
        public string Log_del_hi { get { return log_del_hi; } set { log_del_hi = value; } }
        public string Log_del_hihi { get { return log_del_hihi; } set { log_del_hihi = value; } }
        public string Log_del_lo { get { return log_del_lo; } set { log_del_lo = value; } }
        public string Log_del_lolo { get { return log_del_lolo; } set { log_del_lolo = value; } }
        public string Log_gen_hi { get { return log_gen_hi; } set { log_gen_hi = value; } }
        public string Log_gen_hihi { get { return log_gen_hihi; } set { log_gen_hihi = value; } }
        public string Log_gen_lo { get { return log_gen_lo; } set { log_gen_lo = value; } }
        public string Log_gen_lolo { get { return log_gen_lolo; } set { log_gen_lolo = value; } }
        public string Log_reset_hi { get { return log_reset_hi; } set { log_reset_hi = value; } }
        public string Log_reset_hihi { get { return log_reset_hihi; } set { log_reset_hihi = value; } }
        public string Log_reset_lo { get { return log_reset_lo; } set { log_reset_lo = value; } }
        public string Log_reset_lolo { get { return log_reset_lolo; } set { log_reset_lolo = value; } }
        public string Max_stacked { get { return max_stacked; } set { max_stacked = value; } }
        public string Measurement_unit_id { get { return measurement_unit_id; } set { measurement_unit_id = value; } }
        public string Misc_flags { get { return misc_flags; } set { misc_flags = value; } }
        public string Poll_after_set { get { return poll_after_set; } set { poll_after_set = value; } }
        public string Precision { get { return precision; } set { precision = value; } }
        public string Proc_id { get { return proc_id; } set { proc_id = value; } }
        public string Ptmgmt_proc_id { get { return ptmgmt_proc_id; } set { ptmgmt_proc_id = value; } }
        public string Pt_enabled { get { return pt_enabled; } set { pt_enabled = value; } }
        public string Pt_origin { get { return pt_origin; } set { pt_origin = value; } }
        public string Pt_set_interval { get { return pt_set_interval; } set { pt_set_interval = value; } }
        public string Pt_set_time { get { return pt_set_time; } set { pt_set_time = value; } }
        public string Pt_type { get { return pt_type; } set { pt_type = value; } }
        public string Range_high { get { return range_high; } set { range_high = value; } }
        public string Range_low { get { return range_low; } set { range_low = value; } }
        public string Raw_lim_high { get { return raw_lim_high; } set { raw_lim_high = value; } }
        public string Raw_lim_low { get { return raw_lim_low; } set { raw_lim_low = value; } }
        public string Rep_timeout_hi { get { return rep_timeout_hi; } set { rep_timeout_hi = value; } }
        public string Rep_timeout_hihi { get { return rep_timeout_hihi; } set { rep_timeout_hihi = value; } }
        public string Rep_timeout_lo { get { return rep_timeout_lo; } set { rep_timeout_lo = value; } }
        public string Rep_timeout_lolo { get { return rep_timeout_lolo; } set { rep_timeout_lolo = value; } }
        public string Reset_allowed_hi { get { return reset_allowed_hi; } set { reset_allowed_hi = value; } }
        public string Reset_allowed_hihi { get { return reset_allowed_hihi; } set { reset_allowed_hihi = value; } }
        public string Reset_allowed_lo { get { return reset_allowed_lo; } set { reset_allowed_lo = value; } }
        public string Reset_allowed_lolo { get { return reset_allowed_lolo; } set { reset_allowed_lolo = value; } }
        public string Reset_cond { get { return reset_cond; } set { reset_cond = value; } }
        public string Reset_pt { get { return reset_pt; } set { reset_pt = value; } }
        public string Reset_timeout_hi { get { return reset_timeout_hi; } set { reset_timeout_hi = value; } }
        public string Reset_timeout_hihi { get { return reset_timeout_hihi; } set { reset_timeout_hihi = value; } }
        public string Reset_timeout_lo { get { return reset_timeout_lo; } set { reset_timeout_lo = value; } }
        public string Reset_timeout_lolo { get { return reset_timeout_lolo; } set { reset_timeout_lolo = value; } }
        public string Resource_id { get { return resource_id; } set { resource_id = value; } }
        public string Rev_conv_eq { get { return rev_conv_eq; } set { rev_conv_eq = value; } }
        public string Rollover_val { get { return rollover_val; } set { rollover_val = value; } }
        public string Safety_pt { get { return safety_pt; } set { safety_pt = value; } }
        public string Sample_intv { get { return sample_intv; } set { sample_intv = value; } }
        public string Sample_intv_unit { get { return sample_intv_unit; } set { sample_intv_unit = value; } }
        public string Scan_rate { get { return scan_rate; } set { scan_rate = value; } }
        public string Setpoint_high { get { return setpoint_high; } set { setpoint_high = value; } }
        public string Setpoint_low { get { return setpoint_low; } set { setpoint_low = value; } }
        public string Time_of_day { get { return time_of_day; } set { time_of_day = value; } }
        public string Trig_ck_pt { get { return trig_ck_pt; } set { trig_ck_pt = value; } }
        public string Trig_pt { get { return trig_pt; } set { trig_pt = value; } }
        public string Trig_rel { get { return trig_rel; } set { trig_rel = value; } }
        public string Trig_val { get { return trig_val; } set { trig_val = value; } }
        public string Uafset { get { return uafset; } set { uafset = value; } }
        public string Update_criteria { get { return update_criteria; } set { update_criteria = value; } }
        public string Variance_val { get { return variance_val; } set { variance_val = value; } }
        public string Vars { get { return vars; } set { vars = value; } }

    }
}
